### ISSUE TITLE
Font  not working

### ISSUE THREAD

**Issue by gastonmorixe** [overboming/ZCAnimatedLabel#1]
Hi,

I can't make font prop work. Any idea? The text doesn't show.

Thanks

**Comment by overboming** [comment]
Which font are you using?

**Comment by gastonmorixe** [comment]
system font 30 pix, 50, whatever I set , it doesn't render.

**Comment by overboming** [comment]
Can you show more code? Also please reference the demo on how to set up properly.

**Comment by gastonmorixe** [comment]
Well, I used basic stuff like set init, set font, set text, nothing fancy.
It is working perfectly with attributed string, so now I am using this. :)

**Comment by overboming** [comment]
Well thanks for the feedback, I will look into it.
