### ISSUE TITLE
Set Box Size before set text

### ISSUE THREAD

**Issue by gastonmorixe** [overboming/ZCAnimatedLabel#2]
I am using auto-layout so I need to set the box size before or at same time the text is set. Size to fit is not working for me, I don't know why.

Because I am using NSAttributedText and oficial apple methods to get the proper size are not working always as expected, after researching I found this works great. 

Feel free to consider adding this to get the proper text size at setText time.

``` obj-c
CTFramesetterRef framesetter = CTFramesetterCreateWithAttributedString((__bridge CFAttributedStringRef)attributedString);
CGSize targetSize = CGSizeMake(320, CGFLOAT_MAX);
CGSize fitSize = CTFramesetterSuggestFrameSizeWithConstraints(framesetter, CFRangeMake(0, [attributedString length]),NULL, targetSize, NULL);
CFRelease(framesetter);
```

**Comment by overboming** [comment]
I have changed ZCAnimatedLabel to support auto layout better

**Comment by gastonmorixe** [comment]
great! thanks
